tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/boneyard'
tap 'homebrew/brewdler'
tap 'homebrew/core'
tap 'homebrew/games'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/x11'
tap 'waltarix/customs'
cask 'xquartz'
brew 'xz', args: ['universal']
brew 'pkg-config'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'libpng', args: ['universal']
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'pixman'
brew 'cairo'
brew 'git'
brew 'gobject-introspection'
brew 'atk'
brew 'autoconf'
brew 'automake'
brew 'bar'
brew 'ghc'
brew 'cabal-install'
brew 'cabextract'
brew 'readline'
brew 'calc'
brew 'cmake'
brew 'cmatrix'
brew 'colordiff'
brew 'gmp'
brew 'coreutils'
brew 'cowsay'
brew 'dhex'
brew 'dialog'
brew 'diff-so-fancy'
brew 'docbook'
brew 'faac'
brew 'texi2html'
brew 'icu4c'
brew 'sqlite'
brew 'gdbm'
brew 'makedepend'
brew 'openssl', args: ['universal']
brew 'python'
brew 'yasm'
brew 'x264'
brew 'lame'
brew 'xvid'
brew 'libogg'
brew 'libvorbis'
brew 'speex'
brew 'jpeg', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'webp', args: ['universal']
brew 'ffmpeg', args: ['with-faac']
brew 'flac'
brew 'fortune'
brew 'mpfr'
brew 'libmpc'
brew 'isl'
brew 'gcc'
brew 'gd', args: ['universal']
brew 'gdk-pixbuf'
brew 'git-flow'
brew 'libxml2', args: ['with-python']
brew 'gnome-doc-utils'
brew 'gnu-sed'
brew 'libtasn1', args: ['universal']
brew 'nettle'
brew 'gnutls'
brew 'python3'
brew 'googler'
brew 'gsettings-desktop-schemas'
brew 'libtool', args: ['universal']
brew 'libepoxy'
brew 'harfbuzz'
brew 'pango'
brew 'hicolor-icon-theme'
brew 'jasper', args: ['universal']
brew 'gtk+3'
brew 'little-cms2', args: ['universal']
brew 'imagemagick', args: ['with-x11']
brew 'libao'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'libuv'
brew 'lua'
brew 'mergepbx'
brew 'mysql'
brew 'nyancat'
brew 'p7zip'
brew 'pandoc'
brew 'portaudio'
brew 'portmidi'
brew 'pwgen'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'ruby-build'
brew 'rbenv'
brew 'sane-backends', args: ['universal']
brew 'scrollkeeper'
brew 'sdl2'
brew 'sl'
brew 'thefuck'
brew 'tig'
brew 'timidity'
brew 'tree'
brew 'tty-clock'
brew 'unixodbc'
brew 'unrar'
brew 'vim', args: ['with-lua']
brew 'wget'
brew 'wifi-password'
brew 'wine'
brew 'zenity'
brew 'winetricks'
brew 'wtf'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'
brew 'homebrew/games/mame'
brew 'homebrew/php/php70'
brew 'homebrew/php/php-code-sniffer'
cask 'adobe-air'
cask 'arduino'
cask 'audacity'
cask 'blender'
cask 'dosbox'
cask 'firefox'
cask 'gimp'
cask 'mactex'
cask 'perian'
cask 'pongsaver'
cask 'processing'
cask 'quicktime-player7'
cask 'scratch'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'xscreensaver'
